---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "asdf"
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: "asdf" #{{ template "config_name" . }}
    app.kubernetes.io/component: "config"
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
data: {{ .Values.game_config }}