---

{{- with .Values.launcher }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-launcher" $.Values.name | quote }}
  namespace: {{ $.Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-launcher" $.Values.name | quote }}
    app.kubernetes.io/component: "launcher"
    app.kubernetes.io/part-of: {{ $.Values.name | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-launcher" $.Values.name | quote }}
      app.kubernetes.io/component: "launcher"
      app.kubernetes.io/part-of: {{ $.Values.name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-launcher" $.Values.name | quote }}
        app.kubernetes.io/component: "launcher"
        app.kubernetes.io/part-of: {{ $.Values.name | quote }}
    spec:
      volumes:
        - name: screeps-config
          configMap:
            name: {{ printf "%s-config" $.Values.name | quote }}
      containers:
        - name: {{ printf "%s-launcher" $.Values.name | quote }}
          image: {{ printf "%s:%s" .image .tag | quote }}          
          ports:
            - containerPort: 21025
          env:
            - name: STEAM_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secret" $.Values.name | quote }}
                  key: "steam_key"
          volumeMounts:
            - name: screeps-config
              mountPath: /screeps/config.yml
              subPath: config.yml
  {{- end }}