---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret_name" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "secret_name" . }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: {{ .Chart.Name }}
type: Opaque
data:
  steam_key: {{ printf "%s" .Values.steam_key | b64enc }}