---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "service_name" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "service_name" . | quote }}
    app.kubernetes.io/component: "service"
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ template "launcher_name" . }}
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  ports:
    - port: 21025
      targetPort: 21025
    - port: 21026
      targetPort: 21026
      