---

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" $.Values.name | quote }}
  namespace: {{ $.Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-service" $.Values.name | quote }}
    app.kubernetes.io/component: "service"
    app.kubernetes.io/part-of: {{ $.Values.name | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ printf "%s-launcher" $.Values.name | quote }}
    app.kubernetes.io/part-of: {{ $.Values.name | quote }}
  ports:
    - name: screep1
      port: 21025
      targetPort: 21025
