---

name: "screep-city"
steam_key: "SECRET_STEAM_KEY"
game_config: |
  mods: # Recommended mods
    - screepsmod-auth
    - screepsmod-admin-utils
  bots:
    simplebot: screepsbot-zeswarm
  serverConfig: # This section requires screepsmod-admin-utils to work
    welcomeText: |
      <h1 style="text-align: center;">My Cool Server</h1>
    constants: # Used to override screeps constants
      TEST_CONSTANT: 123
    tickRate: 1000 # In milliseconds. This is a lower bound. Users reported problems when set too low.
  cli: # used for configuring cli client
    host: testing.hosting.screepspl.us
    port: 443 # https assumed when using 443
    username: admin
    password: notARealPassword
  

##################################
### Boring Kubernetes Settings ###
##################################

namespace: screeps

launcher:
  image: screepers/screeps-launcher
  tag: v1.13.2

database:
  mongo_version: 4.2.3
  storage_class_name: kube-rook
  allocated_space: 10Gi

